
@baseurl = http://localhost:3001/db


### Get users

GET {{baseurl}}/users

### GET user by ID
GET {{baseurl}}/users/11111

### GET user groups
GET {{baseurl}}/11111/groups

### POST a new user
POST {{baseurl}}/register/user
Content-Type: application/json

{
    "username": "Thruster69",
    "email": "thruster@gmail.com",
    "password": "thisisfucked"
}

### Login
GET {{baseurl}}/login
Content-Type: application/json

{
    "email": "thruster@gmail.com",
    "password": "thisisfucked"
}