
@baseurl = http://localhost:3001/api


### Get users

GET {{baseurl}}/users

### GET user by ID
GET {{baseurl}}/users/11111

### GET user groups
GET {{baseurl}}/1111/groups

### POST a new user
### This request would fail unless you change the email
POST {{baseurl}}/register/user
Content-Type: application/json

{
    "username": "Thruster69",
    "email": "thruster69@gmail.com",
    "password": "thisisfucked"
}

### Login
POST {{baseurl}}/login
Content-Type: application/json

{
    "email": "thruster@gmail.com",
    "password": "thisisfucked"
}